### ISSUE TITLE
Userlimit exceeded

### ISSUE THREAD

**Issue by Malones777** [open-ic/open-chat#2846]
Hello All
Just tried to register for open-chat and it is somehow turning and turning and on the end I got this message user limit
![Screenshot 2022-12-22 055517](https://user-images.githubusercontent.com/120394905/209060668-1f94af1c-6f68-4349-9e41-2919ef3a9857.jpg) exceeded

Any hints?

Cheers

**Comment by julianjelfs** [comment]
Yes we have hit a temporary registration limit and will be closing registrations again for a short time. Like I said, this is a temporary situation while we scale OpenChat to run on multiple subnets.

**Comment by Malones777** [comment]
Hi Julian, is there a possability to bypass this? I did apply at Dfinity foundation and I had a discussion with Brandon Cohen and he told me to try it. If not ok aswell.

Best regards,
Patrick

**Comment by julianjelfs** [comment]
I'm sorry Patrick, but there isn't really an easy way for us to let just one person in without opening the gates to others which we aren't really in a position to do right at the moment. If you are just trying to get a feel for the IC ecosystem then there are a few other good social apps that you could try such as DSCVR or Distrikt. And we will be back in the near future.

**Comment by Malones777** [comment]
Thank you Julian. Nobissue. I already registered for distrikt and dscvr. I will try again from time to time. Wish you a relaxing x-mas time
