### ISSUE TITLE
Can't see the result of poll which created by myself.

### ISSUE THREAD

**Issue by cryptodriver** [open-ic/open-chat#3060]
As the title shows, I can not see the result of a poll created by myself.

**Comment by julianjelfs** [comment]
Can you be a little bit more specific? Is this an issue to do with the colour scheme or something else? How was the poll configured in the first place? Can you maybe attach a screenshot or (if it is public) a link to the poll message itself?

**Comment by julianjelfs** [comment]
I'm going to close this in the absence of any further information. I'm assuming it was related to a previous color scheme problem which is now fixed. Please re-open if it's something else.
