### ISSUE TITLE
YouTube video embedding uses the wrong syntax for start time

### ISSUE THREAD

**Issue by julianjelfs** [open-ic/open-chat#3425]
Need to translate any `t=xxx` query string param into a `start=xxx` param for the iframe. 

https://developers.google.com/youtube/player_parameters#start

Change needs to be made in [here](https://github.com/open-ic/open-chat/blob/master/frontend/app/src/components/home/TextContent.svelte)

**Comment by yadavsairaj** [comment]
Do you want to start the embedded video to start at some specific time?
